//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Drilltab.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_DS_CROSS                    102
#define IDS_DS_FIRST                    102
#define IDD_DTAPP_DLG                   102
#define IDS_DS_X                        103
#define IDS_DS_Y                        104
#define IDS_DS_T                        105
#define IDS_DS_HOUR                     106
#define IDS_DS_SIDE_HOUR                107
#define IDS_DS_BOX_LINE                 108
#define IDS_DS_DIAMOND_LINE             109
#define IDS_DS_BOX_V                    110
#define IDS_DS_DIAMOND_V                111
#define IDS_DS_BOX_X                    112
#define IDS_DS_DIAMOND_CROSS            113
#define IDS_DS_BOX_CROSS                114
#define IDS_DS_DIAMOND_X                115
#define IDS_DS_BOX_Y                    116
#define IDS_DS_DIAMOND_Y                117
#define IDS_DS_BOX_T                    118
#define IDS_DS_DIAMOND_T                119
#define IDS_DS_CIRCLE_LINE              120
#define IDS_DS_CIRCLE_V                 121
#define IDS_DS_CIRCLE_CROSS             122
#define IDS_DS_CIRCLE_X                 123
#define IDS_DS_CIRCLE_Y                 124
#define IDS_DS_CIRCLE_T                 125
#define IDS_DS_UPPER_A                  126
#define IDS_DS_UPPER_B                  127
#define IDS_DS_UPPER_C                  128
#define IDS_DS_UPPER_D                  129
#define IDS_DS_UPPER_E                  130
#define IDS_DS_UPPER_F                  131
#define IDS_DS_UPPER_G                  132
#define IDS_DS_UPPER_H                  133
#define IDS_DS_UPPER_I                  134
#define IDS_DS_UPPER_J                  135
#define IDS_DS_UPPER_K                  136
#define IDS_DS_UPPER_L                  137
#define IDS_DS_UPPER_M                  138
#define IDS_DS_UPPER_N                  139
#define IDS_DS_UPPER_O                  140
#define IDS_DS_UPPER_P                  141
#define IDS_DS_UPPER_Q                  142
#define IDS_DS_UPPER_R                  143
#define IDS_DS_UPPER_S                  144
#define IDS_DS_UPPER_U                  145
#define IDS_DS_UPPER_V                  146
#define IDS_DS_UPPER_W                  147
#define IDS_DS_UPPER_Z                  148
#define IDS_DS_LOWER_A                  149
#define IDS_DS_LOWER_B                  150
#define IDS_DS_LOWER_C                  151
#define IDS_DS_LOWER_D                  152
#define IDS_DS_LOWER_E                  153
#define IDS_DS_LOWER_F                  154
#define IDS_DS_LOWER_G                  155
#define IDS_DS_LOWER_H                  156
#define IDS_DS_LOWER_I                  157
#define IDS_DS_LOWER_J                  158
#define IDS_DS_LOWER_K                  159
#define IDS_DS_LOWER_L                  160
#define IDS_DS_LOWER_M                  161
#define IDS_DS_LOWER_N                  162
#define IDS_DS_LOWER_O                  163
#define IDS_DS_LOWER_P                  164
#define IDS_DS_LOWER_Q                  165
#define IDS_DS_LOWER_R                  166
#define IDS_DS_LOWER_S                  167
#define IDS_DS_LOWER_T                  168
#define IDS_DS_LOWER_U                  169
#define IDS_DS_LOWER_V                  170
#define IDS_DS_LOWER_W                  171
#define IDS_DS_LOWER_Y                  172
#define IDS_DS_LOWER_Z                  173
#define IDR_MENU1                       174
#define IDD_STATUS_DLG                  175
#define IDI_DRILLTAB1                   176
#define IDI_DRILLTAB2                   177
#define IDI_DRILLTAB3                   178
#define IDPB_OK                         1000
#define IDGR_DTPREVIEW                  1005
#define IDEB_TITLE                      1026
#define IDEB_LINEWIDTH                  1027
#define IDEB_XLOC                       1028
#define IDCB_LAYER                      1029
#define IDCB_TEXTSTYLE                  1030
#define IDEB_YLOC                       1031
#define IDRB_LOCUPLEFT                  1032
#define IDRB_LOCLOWLEFT                 1033
#define IDRB_LOCUPRIGHT                 1034
#define IDRB_LOCLOWRIGHT                1035
#define IDEB_COLLABEL                   1036
#define IDEB_COLMINWIDTH                1037
#define IDPB_COLADD                     1038
#define IDPB_COLDELETE                  1039
#define IDGB_LOCATION                   1040
#define IDST_LINEWIDTH                  1041
#define IDST_LAYER                      1042
#define IDST_TEXTSTYLE                  1043
#define IDGB_HDUNITS                    1044
#define IDST_XLOC                       1045
#define IDST_YLOC                       1046
#define IDGB_COLUMN                     1047
#define IDST_COLLABEL                   1048
#define IDST_COLMINWIDTH                1049
#define IDST_TITLE                      1050
#define IDPB_CANCEL                     1051
#define IDRB_HDUNITSIN                  1054
#define IDRB_HDUNITSMM                  1055
#define IDST_STATUS_MSG                 1056
#define IDC_CUSTOM1                     1060
#define IDM_FILE_EXIT                   32771
#define IDM_HELP_ABOUT                  32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
